# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: my-backend  # Local backend image you loaded into Kind
        ports:
        - containerPort: 5000  # Assuming backend is running on port 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort  # Use NodePort for Kind cluster
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000  # Mapping port 80 on the NodePort to 5000 on the container
    nodePort: 30002   # Exposing backend service on localhost:30002
